### ISSUE TITLE
Non-working file access rights after installation

### ISSUE THREAD

**Issue by jurajkapsz** [pointybeard/symphonycms#11]
Files created during master branch installation, i.e. `/manifest/logs/install` and `/manifest/config.json`, are further inaccessible for CMS, making the CMS unusable.

## Expected Behavior

I asume, files should have access rights defined by the installer, which should be **0644** by default for files.

```sh
-rw-r--r--
```

## Actual Behavior

Files have access rights of **0204, including a sticky bit permission**.

```bash
--w----r-T
```
CMS does not work.

When I have commented out this [chmod call](https://github.com/pointybeard/symphonycms/blob/4e9f944be33b0623ebe049c27d813c371179f14f/symphony/lib/core/class.log.php#L105) prior the installation, the `install` log file retained `0644` access rights and was working fine.

After manually reseting the `config.json` file access rights to `0644`, SCMS was working fine.

## Steps to Reproduce the Problem

1. Following [master installation instructions](https://github.com/pointybeard/symphonycms#master).

## Your Environment

* Version used: SCMS Extended v2.7.10
* Browser Name and Version: Chromium v94
* Operating System and Version (desktop or mobile): Xubuntu 20.04 LTS
* PHP: v7.4.24

**Comment by pointybeard** [comment]
This should be directed at the official Symphony CMS repo: <https://github.com/symphonycms/symphonycms>. My fork is highly experimental and the install feature of Symphony CMS hasn't been tested or updated to reflect my changes.
