### ISSUE TITLE
Symphony Takeover?

### ISSUE THREAD

**Issue by animaux** [pointybeard/symphonycms#4]
Hi Alannah, 

since the official Symphony repo is pretty much dead for some time with no hope of receiving any updates – I wonder if you would be interested in either taking over the main repo or opening another possibility to give existing symphony sites a future again. 

I guess this repo kind of does the latter. I still have to try your extended version. Does it already support PHP8? I wonder about extension compatibility.

There has been some talk about the future of Symphony in the gitter chat, but I can understand if you don’t want to get involved there https://gitter.im/symphonycms/symphony-2 More and more people abandon Symphony for obvious reasons, there’s only a very small group left and everyone has their own patched version … 

Sorry if this a confusing »Feature Request« Just hoping for some future for Symphony, and a word from you would be nice to hear.

All the best, 

Alex

**Comment by pointybeard** [comment]
I am not really keen on taking over the official Symphony repo. Been there, done that! 😉  If people start to gravitate to what I am doing, that's cool. And I am happy to accept PRs and such.

This fork was mostly to facilitate my work on [Orchestra](https://github.com/pointybeard/orchestra), and some libraries I have produced like [Symphony Classmapper](https://github.com/pointybeard/symphony-classmapper), [XSLT 3 support](https://github.com/pointybeard/saxon), and [Section Builder](https://github.com/pointybeard/symphony-section-builder), none of which would work using a vanilla 2.7.10LTS install.

As for PHP8, currently there isn't support, but, it's something I would like to work on. I am just concerned about extension compatibility.

> Just hoping for some future for Symphony, and a word from you would be nice to hear.

I use this fork, as well as my collection of libraries and extensions, daily as part of my job. I cannot speak to the future of Symphony in an official capacity since I am not involved anymore, however, aim is to continue using Symphony and slowly modernize the code base without creating compatibility issues (if I can avoid it).

**Comment by animaux** [comment]
Thanks for your feedback!

I perfectly understand your position. As things currently stand there is practically no one involved »officially« anymore. Your fork and your plans to »slowly modernize the code base« sound like a good way to go forward.

@pixelninja and @petertron did some work on updating stuff for PHP 8. That feels the next big hurdle on the way, and I’m hopeful that fixes for most extensions will be comparable to the ones for PHP 7.

I’d love to be able to continue to use Symphony in the future too, I have yet to come across a CMS that can keep up with it. Also because I’m starting to get old and grumpy `;)`.

**Comment by pointybeard** [comment]
> Also because I’m starting to get old and grumpy

I know the feeling!

Very roughly, my plan is to do a major codebase restructure while maintaining as much backwards compatibility as possible. I am tentatively calling this 2.8 for now. You can see the progress in the `wip-2.8.x` branch. Once this is done, I will start refactoring the internal code, again, maintaining as much backwards compatibility as possible.

I'd like to properly integrate my [symphony-classmapper](https://github.com/pointybeard/symphony-classmapper), [symphony-extended](https://github.com/pointybeard/symphony-extended), [symphony-section-builder](https://github.com/pointybeard/symphony-section-builder), [console](https://github.com/pointybeard/console), [symext-section-model-builder](https://github.com/pointybeard/symext-section-model-builder) and [symphony-pdo](https://github.com/pointybeard/symphony-pdo) libraries, as well as some of the middleware related stuff I've done in [api_framework](https://github.com/pointybeard/api_framework).

This then gives me a good platform to start thinking about PHP8 and some more drastic change. e.g. ripping out all of the old page routing code, decoupling "Administration" and "Frontend" from the core Symphony kernel, introduce better dependency injection, rewriting the logger code and a few other things.

The list is long! But, I am hoping to keep chipping away at it.

**Comment by animaux** [comment]
Yes, that’s quite an impressive list, but sound really great! 

Since I am a designer and only 1/16 of a programmer, I have yet to understand how your libraries integrate and work together with symphony. But I can understand what it does, so I am very much looking forward to this development. Sadly most of my customers sites are on shared webservers without console access, so alt least that stuff sadly wont work for me.

I will try out your fork as soon as time allows, thanks for all your work!

**Comment by animaux** [comment]
Here is @pixelninja’s PHP8 patch for symphony: https://github.com/pixelninja/symphonycms-php8, including a quite comprehensive set of extensions as well!

**Comment by pointybeard** [comment]
I’ll take a look. Unfortunately there is no commit history as it’s just a dump of files, so its trickier to see what’s changed. Still, should be useful.

**Comment by animaux** [comment]
I have just dumped it into BBEdits folder comparison tool, and there are quite a lot of changes, most of them seem to be comparable to PHP7-patches in the past, as far as I can tell.

There’s also @petertron’s fork with patches for PHP8, but that starts from version 3.0.0: https://github.com/petertron/symphonycms

**Comment by pointybeard** [comment]
To be honest, I am starting to migrate away from Symphony. There are too many other frameworks out there that are well maintained, documented, tested, and run on PHP 8.0 to ignore. I might still tinker with things and I am maintaining some legacy systems that run on my Symphony build, but, I doubt I'll have time for active development here anytime soon.

**Comment by animaux** [comment]
Fair enough, thanks for getting back and all the best!
