### ISSUE TITLE
Composer Problem

### ISSUE THREAD

**Issue by animaux** [pointybeard/symphonycms#5]
> $ composer update -vv --no-dev --profile -d ./symphonycms

When running the composer command after cloning the repo I get the following error:

```
Your requirements could not be resolved to an installable set of packages.
Root composer.json requires php >=7.4 but your php version (7.3.11) does not satisfy that requirement.
```

However I am running MAMP with PHP 7.4.12 on a Mac with macOS 10.15.7.

**Comment by animaux** [comment]
When changing to `"php": ">=7.3"` it runs. So I would guess it is just some version recognition problem.

**Comment by pointybeard** [comment]
It's likely that your command line version of PHP is 7.3 but the MAMP version is 7.4. What do you get on the command line when you run the command `php -v`?

**Comment by animaux** [comment]
> It's likely that your command line version of PHP is 7.3 but the MAMP version is 7.4. What do you get on the command line when you run the command `php -v`?

Point on! `;)` Thanks!
